const SET_SNEAKERS = 'SET_SNEAKERS';
const SET_IS_LOADING_SNEAKERS = 'SET_IS_LOADING_SNEAKERS';
const SET_ERROR_SNEAKERS = 'SET_ERROR_SNEAKERS';
const CLEAR_ERROR_SNEAKERS = 'CLEAR_ERROR_SNEAKERS';
const CLEAR_ALL_SNEAKERS = 'CLEAR_ALL_SNEAKERS';
const SET_CART = 'SET_CART';

export {
    SET_SNEAKERS,
    SET_IS_LOADING_SNEAKERS,
    SET_ERROR_SNEAKERS,
    CLEAR_ERROR_SNEAKERS,
    CLEAR_ALL_SNEAKERS,
    SET_CART,
};
